# Generated by Django 4.0 on 2022-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cet_scorecard',
            new_name='matric_certificate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='hsc_percentage',
            new_name='matric_percentage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cet_percentile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hsc_leaving_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hsc_marksheet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hsc_passing_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='jee_percentile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='jee_scorecard',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_leaving_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_marksheet',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_passing_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_percentage',
        ),
        migrations.AddField(
            model_name='application',
            name='highest_grade',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
